<figure>
   <IMG SRC="https://mamba-python.nl/images/logo_basis.png" WIDTH=125 ALIGN="right">
</figure>
    
# GIS visualisation

In this notebook we will work together to make an application that combines the data from an xml, a csv and a shapfile into one graphical map.

<br>
<br>
<div style="text-align: right"> developed by MAMBA </div>

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
from datetime import datetime
import pandas as pd
import xml.etree.ElementTree as ET
import geopandas as gpd
import contextily as ctx

### Constants and relative paths to files

In [2]:
# read shapefile with the actual location of the canals
boezem = r"shapefiles/boezemwatergangen.shp"

# read shapefile with the modelled canals
RTCtakken = r"shapefiles/RTC takken voorstel 20160203.shp"

# read csv file with initial water levels
csv_file_time = 'timeseries_0000.csv'

# read an xml file with the model configuration (node coördinates and their names)
csv_file_coords = 'coordinates.csv'
# ns = "{http://www.wldelft.nl/fews}" #standard code, created by the software 


ref_system_xml = 'EPSG:28992'
ref_basemap = 3857

In [3]:
df_coords = pd.read_csv(csv_file_coords, index_col=0)

df_coords.head()

           x          y
N1  71538.62  441142.57
N4  70545.79  448791.50
N5  70590.09  448741.04
N7  71573.05  441316.86
N8  71606.43  441355.23

In [4]:
df_wl = pd.read_csv(csv_file_time)

for col in df_wl.columns:
    if '_HRTC' in col:
        wl = df_wl.loc[0, col]
        col_split = col.split('_')[0]
        df_coords.loc[col_split, 'ini_wl_HRTC'] = wl

df_coords.head()

           x          y  ini_wl_HRTC
N1  71538.62  441142.57       -0.360
N4  70545.79  448791.50       -0.360
N5  70590.09  448741.04       -0.480
N7  71573.05  441316.86       -0.360
N8  71606.43  441355.23       -0.469

In [5]:
points = gpd.points_from_xy(df_coords.x, df_coords.y, crs=ref_system_xml)
gdf = gpd.GeoDataFrame(df_coords, geometry=points)

In [6]:
gdf.head()
gdf = gdf.to_crs(ref_basemap)

In [7]:
gdf.explore(column=gdf.ini_wl_HRTC)